displayName: IP2Location plugin
type: middleware

import: github.com/r3dm4st3r/traefik-plugin-ip2location

summary: '[geoip] Add Geo Headers from IP2Location'

testData:
  fromHeader: 'X-Custom-IP'
  filename: 'IP2LOCATION-LITE-DB11.BIN'
  # Flattened header configuration (no nested "headers:" for Yaegi compatibility)
  country_code: X-GEO-Country-Code
  country_name: X-GEO-Country-Name
  region: X-GEO-Region
  region_code: X-GEO-Region-Code
  city: X-GEO-City
  postal_code: X-GEO-Postal-Code
  latitude: X-GEO-Latitude
  longitude: X-GEO-Longitude
  timezone: X-GEO-TimeZone
  continent_code: X-GEO-Continent-Code
  continent_name: X-GEO-Continent-Name
  isp: X-GEO-ISP
  asn: X-GEO-ASN
  asn_organization: X-GEO-ASN-Org
  domain: X-GEO-Domain
  connection_type: X-GEO-Connection-Type
  user_type: X-GEO-User-Type
  accuracy_radius: X-GEO-Accuracy-Radius
