displayName: MaxMind GeoIP2 plugin
type: middleware

import: github.com/r3dm4st3r/traefik-plugin-ip2location

summary: '[geoip] Add Geo Headers from MaxMind'

testData:
  fromHeader: 'X-Custom-IP'
  filename: 'GeoLite2-City.mmdb'
  headers:
    CountryCode: X-GEO-Country-Code
    CountryName: X-GEO-Country-Name
    Region: X-GEO-Region
    RegionCode: X-GEO-Region-Code
    City: X-GEO-City
    PostalCode: X-GEO-Postal-Code
    Latitude: X-GEO-Latitude
    Longitude: X-GEO-Longitude
    Timezone: X-GEO-TimeZone
    ContinentCode: X-GEO-Continent-Code
    ContinentName: X-GEO-Continent-Name
    Isp: X-GEO-ISP
    Asn: X-GEO-ASN
    AsnOrganization: X-GEO-ASN-Org
    Domain: X-GEO-Domain
    ConnectionType: X-GEO-Connection-Type
    UserType: X-GEO-User-Type
    AccuracyRadius: X-GEO-Accuracy-Radius
